services:

  # ===============================
  # PostgreSQL para AUTH service
  # ===============================
  postgres_auth:
    image: postgres:15
    container_name: postgres_auth
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: ${DB_AUTH_USER}
      POSTGRES_PASSWORD: ${DB_AUTH_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL para USER service
  # ===============================
  postgres_user:
    image: postgres:15
    container_name: postgres_user
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: ${DB_USER_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASS}
    ports:
      - "5435:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL para ACCOUNT service
  # ===============================
  postgres_account:
    image: postgres:15
    container_name: postgres_account
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: ${DB_ACCOUNT_USER}
      POSTGRES_PASSWORD: ${DB_ACCOUNT_PASS}
    ports:
      - "5436:5432"
    volumes:
      - pgdata_account:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL para TRANSACTION service
  # ===============================
  postgres_transaction:
    image: postgres:15
    container_name: postgres_transaction
    environment:
      POSTGRES_DB: transaction
      POSTGRES_USER: ${DB_TRANSACTION_USER}
      POSTGRES_PASSWORD: ${DB_TRANSACTION_PASS}
    ports:
      - "5437:5432"
    volumes:
      - pgdata_transaction:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL para KEYCLOAK
  # ===============================
  postgres_keycloak:
    image: postgres:15
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DB_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${DB_KEYCLOAK_PASS}
    ports:
      - "5434:5432"
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data

  # ===============================
  # KEYCLOAK server
  # ===============================
  keycloak_server:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak-server
    command: start-dev
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${DB_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${DB_KEYCLOAK_PASS}
      # KC URL in api-gateway
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
    ports:
      - "8091:8080"
    depends_on:
      - postgres_keycloak

  # ===============================
  # RabbitMQ
  # ===============================
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # ===============================
  # CONFIG SERVER 
  # ===============================
  config-server:
    image: eclipse-temurin:21-jdk-alpine
    container_name: config-server
    working_dir: /app
    volumes:
      - ./infraestructure-domain/config-server/target/config-server-exec.jar:/app/config-server.jar
      - ./infraestructure-domain/config-repo:/config-repo
    command: ["java", "-jar", "/app/config-server.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:///config-repo
      EUREKA_SERVER: http://eureka-server:8761/eureka
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  # ===============================
  # EUREKA SERVER 
  # ===============================
  eureka-server:
    image: eclipse-temurin:21-jdk-alpine
    container_name: eureka-server
    working_dir: /app
    volumes:
      - ./infraestructure-domain/eureka/target/eureka-exec.jar:/app/eureka-server.jar
    command: ["java", "-jar", "/app/eureka-server.jar"]
    ports:
      - "8761:8761"
    depends_on:
      - postgres_auth
      - postgres_user

  # ===============================
  # API GATEWAY 
  # ===============================
  api-gateway:
    image: eclipse-temurin:21-jdk-alpine
    container_name: api-gateway
    working_dir: /app
    volumes:
      - ./infraestructure-domain/api-gateway/target/api-gateway-exec.jar:/app/api-gateway.jar
    command: ["java", "-jar", "/app/api-gateway.jar"]
    environment:
      EUREKA_SERVER: http://eureka-server:8761/eureka
      KEYCLOAK_SERVER: http://keycloak-server:8080
      KEYCLOAK_JWKS_URL: http://api-gateway:8080/realms/SpringNeoBank/protocol/openid-connect/certs
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
      - keycloak_server

volumes:
  pgdata:
  pgdata_user:
  pgdata_account:
  pgdata_keycloak:
  pgdata_transaction:
  rabbitmq_data: