services:

  # ===============================
  # Base image for Spring Boot Projects
  # ===============================
  maven-base:
    build:
      context: .
      dockerfile: docker/maven-base.Dockerfile
    image: springneobank-maven
    
  # ===============================
  # PostgreSQL for AUTH service
  # ===============================
  postgres_auth:
    image: postgres:15
    container_name: postgres_auth
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: ${DB_AUTH_USER}
      POSTGRES_PASSWORD: ${DB_AUTH_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL for USER service
  # ===============================
  postgres_user:
    image: postgres:15
    container_name: postgres_user
    environment:
      POSTGRES_DB: uer
      POSTGRES_USER: ${DB_USER_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASS}
    ports:
      - "5435:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL para ACCOUNT service
  # ===============================
  postgres_account:
    image: postgres:15
    container_name: postgres_account
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: ${DB_ACCOUNT_USER}
      POSTGRES_PASSWORD: ${DB_ACCOUNT_PASS}
    ports:
      - "5436:5432"
    volumes:
      - pgdata_account:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL para TRANSACTION service
  # ===============================
  postgres_transaction:
    image: postgres:15
    container_name: postgres_transaction
    environment:
      POSTGRES_DB: transaction
      POSTGRES_USER: ${DB_TRANSACTION_USER}
      POSTGRES_PASSWORD: ${DB_TRANSACTION_PASS}
    ports:
      - "5437:5432"
    volumes:
      - pgdata_transaction:/var/lib/postgresql/data

  # ===============================
  # PostgreSQL for Keycloak Server
  # ===============================
  postgres_keycloak:
    image: postgres:15
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DB_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${DB_KEYCLOAK_PASS}
    ports:
      - "5434:5432"
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data

  # ===============================
  # KEYCLOAK server
  # ===============================
  keycloak_server:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak-server
    command: start-dev
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${DB_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${DB_KEYCLOAK_PASS}
      # KC URL in api-gateway
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
    ports:
      - "8091:8080"
    depends_on:
      - postgres_keycloak

  # ===============================
  # RabbitMQ
  # ===============================
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # ===============================
  # Service CONFIG SERVER
  # ===============================
  config-server:
    build: 
      context: ./infraestructure-domain/config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:///config-repo
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      #- CONFIG_USER=admin
      #- CONFIG_PASSWORD=admin123
    depends_on:
      - maven-base
      - eureka-server
    volumes:
      - ./infraestructure-domain/config-repo:/config-repo

  # ===============================
  # Service EUREKA
  # ===============================
  eureka-server:
    build:
      context: ./infraestructure-domain/eureka
      dockerfile: Dockerfile
      args:
        MAVEN_BASE_IMAGE: springneobank-maven
    container_name: eureka-server
    depends_on:
      - postgres_auth
      - maven-base
    ports:
      - "8761:8761"

  # ===============================
  # Service API-GATEWAY
  # ===============================
  api-gateway:
    build:
      context: ./infraestructure-domain/api-gateway
      dockerfile: Dockerfile
      args:
        MAVEN_BASE_IMAGE: springneobank-maven
    container_name: api_gateway
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - KEYCLOAK_SERVER=http://keycloak-server:8080
      - KEYCLOAK_JWKS_URL=http://api-gateway:8080/realms/SpringNeoBank/protocol/openid-connect/certs
    depends_on:
      - maven-base
      - eureka-server
      - keycloak_server
    ports:
      - "8080:8080"

  # ===============================
  # Service AUTH
  # ===============================
  auth:
    build:
      context: ./business-domain/auth
      dockerfile: Dockerfile
      args:
        MAVEN_BASE_IMAGE: springneobank-maven
    container_name: auth_service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - DB_NAME=auth
      - DB_AUTH_USER=${DB_AUTH_USER}
      - DB_AUTH_PASS=${DB_AUTH_PASS}
      - KC_SERVER=http://api_gateway:8080
      - KC_REALM_ID=oss1hknLoJugUGEdVXIOxM76RgLYswx9K0Zs236Z414
      - KC_CLIENT_ADMIN_ID=auth
      - KC_CLIENT_ADMIN_SECRET=DUxP5WZYGlnLRXz7xhKzW2IpbrVk4EdD
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      #- CONFIG_USER=admin
      #- CONFIG_PASSWORD=admin123
    depends_on:
      - postgres_auth
      - config-server
      - maven-base
      - eureka-server
      - keycloak_server
    ports:
      - "8081:8081"

  # ===============================
  # Service USER
  # ===============================
  user:
    build:
      context: ./business-domain/user
      dockerfile: Dockerfile
      args:
        MAVEN_BASE_IMAGE: springneobank-maven
    container_name: user_service
    environment:
      - DB_HOST=jdbc:postgresql://postgres_user:5432
      - DB_NAME=user
      - DB_USER_USER=${DB_USER_USER}
      - DB_USER_PASS=${DB_USER_PASS}
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    depends_on:
      - postgres_user
      - config-server
      - maven-base
      - eureka-server
    ports:
      - "8082:8082"

  # ===============================
  # Service ACCOUNT
  # ===============================
  account:
    build:
      context: ./business-domain/account
      dockerfile: Dockerfile
      args:
        MAVEN_BASE_IMAGE: springneobank-maven
    container_name: account_service
    environment:
      - DB_HOST=jdbc:postgresql://postgres_account:5432
      - DB_NAME=account
      - DB_ACCOUNT_USER=${DB_ACCOUNT_USER}
      - DB_ACCOUNT_PASS=${DB_ACCOUNT_PASS}
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    depends_on:
      - postgres_account
      - config-server
      - maven-base
      - eureka-server
    ports:
      - "8083:8083"

  # ===============================
  # Service TRANSACTION
  # ===============================
  transaction:
    build:
      context: ./business-domain/transaction
      dockerfile: Dockerfile
      args:
        MAVEN_BASE_IMAGE: springneobank-maven
    container_name: transaction_service
    environment:
      - DB_HOST=jdbc:postgresql://postgres_transaction:5432
      - DB_NAME=transaction
      - DB_TRANSACTION_USER=${DB_TRANSACTION_USER}
      - DB_TRANSACTION_PASS=${DB_TRANSACTION_PASS}
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - RABBIT_HOST=rabbitmq
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    depends_on:
      - postgres_transaction
      - config-server
      - maven-base
      - eureka-server
    ports:
      - "8084:8084"

volumes:
  pgdata:
  pgdata_keycloak:
  pgdata_user:
  pgdata_account:
  pgdata_transaction:
  rabbitmq_data: