spring:
  application:
    name: businessdomain-auth
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

  cloud:
    config:
      name: auth
      profile: ${SPRING_PROFILES_ACTIVE:local}
      enabled: true
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

keycloak:
  realm: SpringNeoBank
  certs-id: ${KC_REALM_ID}
  client-id: ${KC_CLIENT_ADMIN_ID}
  client-secret: ${KC_CLIENT_ADMIN_SECRET}

  base-uri: ${KC_SERVER:http://localhost:8091/}
  admin-token-uri: ${keycloak.base-uri}/realms/master/protocol/openid-connect/token
  users-uri: ${keycloak.base-uri}/admin/realms/${keycloak.realm}/users
  user-info-uri: ${keycloak.base-uri}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
  jwk-set-uri: ${keycloak.base-uri}/realms/${keycloak.realm}/protocol/openid-connect/certs
  change-password-uri: ${keycloak.users-uri}/*user*/reset-password

#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        web: DEBUG
#      springneobank: DEBUG